/** AUTO-GENERATED by scripts/generate_ws_types.py — do not edit manually. */

export interface ConnectedWsEvent {
  type: "connected";
  port?: number;
  version?: string;
  auth_required?: boolean;
}

export interface AuthOkWsEvent {
  type: "auth.ok";
}

export interface PongWsEvent {
  type: "pong";
}

export interface TokenWsEvent {
  type: "token";
  thread_id?: string;
  content?: string;
}

export interface ToolProgressWsEvent {
  type: "tool_progress";
  thread_id?: string;
  tool_name?: string;
  tool_call_id?: unknown;
  status?: string;
}

export interface ToolStartWsEvent {
  type: "tool_start";
  thread_id?: string;
  name?: string;
  args?: Record<string, unknown>;
  category?: unknown;
  tool_call_id?: unknown;
}

export interface ToolEndWsEvent {
  type: "tool_end";
  thread_id?: string;
  name?: string;
  result?: string;
  category?: unknown;
  tool_call_id?: unknown;
  citations?: unknown;
}

export interface InterruptWsEvent {
  type: "interrupt";
  thread_id?: string;
  action?: string;
  preview?: string;
  args?: Record<string, unknown>;
}

export interface InterruptTimeoutWarningWsEvent {
  type: "interrupt_timeout_warning";
  thread_id?: string;
  seconds_left?: number;
}

export interface DoneWsEvent {
  type: "done";
  thread_id?: string;
  metadata?: unknown;
}

export interface TasksChangedWsEvent {
  type: "tasks.changed";
  reason?: string;
}

export interface SchedulerReminderWsEvent {
  type: "scheduler.reminder";
  title?: string;
  message?: string;
}

export interface SessionArchivedWsEvent {
  type: "session.archived";
  sessions?: Record<string, unknown>[];
}

export interface SessionArchivedOneWsEvent {
  type: "session.archived_one";
  thread_id?: string;
  ok?: boolean;
}

export interface SessionUnarchivedOneWsEvent {
  type: "session.unarchived_one";
  thread_id?: string;
  ok?: boolean;
}

export interface ErrorWsEvent {
  type: "error";
  message?: string;
  code?: unknown;
  thread_id?: unknown;
}

export interface SessionListWsEvent {
  type: "session.list";
  sessions?: Record<string, unknown>[];
}

export interface SessionCreatedWsEvent {
  type: "session.created";
  thread_id?: string;
  title?: string;
  created_at?: string;
}

export interface SessionDeletedWsEvent {
  type: "session.deleted";
  thread_id?: string;
  ok?: unknown;
}

export interface SessionHistoryWsEvent {
  type: "session.history";
  thread_id?: string;
  messages?: Record<string, unknown>[];
}

export interface RagListWsEvent {
  type: "rag.list";
  sources?: string[];
}

export interface RagIngestWsEvent {
  type: "rag.ingest";
  result?: string;
}

export interface RagSearchWsEvent {
  type: "rag.search";
  query?: unknown;
  results?: Record<string, unknown>[];
}

export interface RagDeletedWsEvent {
  type: "rag.deleted";
  source?: unknown;
  ok?: unknown;
}

export interface ChatStoppedWsEvent {
  type: "chat.stopped";
  thread_id?: string;
  ok?: boolean;
}

export interface MemoryGetWsEvent {
  type: "memory.get";
  namespace?: string;
  key?: string;
  value?: unknown;
}

export interface MemorySetWsEvent {
  type: "memory.set";
  namespace?: string;
  key?: string;
  ok?: boolean;
}

export interface SchedulerListWsEvent {
  type: "scheduler.list";
  jobs?: Record<string, unknown>[];
}

export type SidecarWsServerMessage =
  | ConnectedWsEvent
  | AuthOkWsEvent
  | PongWsEvent
  | TokenWsEvent
  | ToolProgressWsEvent
  | ToolStartWsEvent
  | ToolEndWsEvent
  | InterruptWsEvent
  | InterruptTimeoutWarningWsEvent
  | DoneWsEvent
  | TasksChangedWsEvent
  | SchedulerReminderWsEvent
  | SessionArchivedWsEvent
  | SessionArchivedOneWsEvent
  | SessionUnarchivedOneWsEvent
  | ErrorWsEvent
  | SessionListWsEvent
  | SessionCreatedWsEvent
  | SessionDeletedWsEvent
  | SessionHistoryWsEvent
  | RagListWsEvent
  | RagIngestWsEvent
  | RagSearchWsEvent
  | RagDeletedWsEvent
  | ChatStoppedWsEvent
  | MemoryGetWsEvent
  | MemorySetWsEvent
  | SchedulerListWsEvent;

export type SidecarWsMessage = SidecarWsServerMessage;
