#!/usr/bin/env python3
"""Generate src/types/wsEvents.generated.ts from agent/src/api/ws_protocol.py."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Union, get_args, get_origin

ROOT = Path(__file__).resolve().parents[1]
AGENT_SRC = ROOT / "agent" / "src"
if str(AGENT_SRC) not in sys.path:
    sys.path.insert(0, str(AGENT_SRC))

from pydantic import BaseModel  # noqa: E402

from api.ws_protocol import SERVER_EVENT_MODELS, export_ws_protocol_json  # noqa: E402

OUT = ROOT / "src" / "types" / "wsEvents.generated.ts"


def _ts_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    if origin is Union:
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return f"{_ts_type(args[0])} | null"
        return " | ".join(_ts_type(a) for a in args)
    if annotation is str:
        return "string"
    if annotation is int:
        return "number"
    if annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is Any:
        return "unknown"
    if origin is list:
        (inner,) = get_args(annotation) or (Any,)
        return f"{_ts_type(inner)}[]"
    if origin is dict:
        return "Record<string, unknown>"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return _interface_name(annotation)
    return "unknown"


def _interface_name(model: type[BaseModel]) -> str:
    return model.__name__.replace("Event", "WsEvent").replace("Metadata", "WsMetadata")


def _emit_interface(model: type[BaseModel], emitted: set[str]) -> list[str]:
    name = _interface_name(model)
    if name in emitted:
        return []
    emitted.add(name)
    lines: list[str] = []
    for field_name, field in model.model_fields.items():
        ann = field.annotation
        if isinstance(field.annotation, type) and issubclass(field.annotation, BaseModel):
            lines.extend(_emit_interface(field.annotation, emitted))
    lines.append(f"export interface {name} {{")
    for field_name, field in model.model_fields.items():
        ann = field.annotation
        ts = _ts_type(ann)
        if field_name == "type":
            default = field.default
            if default is not None:
                ts = json.dumps(default)
            optional = ""
        elif field.is_required() and field.default is None and field.default_factory is None:
            optional = ""
        else:
            optional = "?"
        lines.append(f"  {field_name}{optional}: {ts};")
    lines.append("}")
    lines.append("")
    return lines


def generate_ts() -> str:
    emitted: set[str] = set()
    parts = [
        "/** AUTO-GENERATED by scripts/generate_ws_types.py — do not edit manually. */",
        "",
    ]
    union_names: list[str] = []
    for model in SERVER_EVENT_MODELS:
        parts.extend(_emit_interface(model, emitted))
        union_names.append(_interface_name(model))
    parts.append("export type SidecarWsServerMessage =")
    for i, name in enumerate(union_names):
        sep = ";" if i == len(union_names) - 1 else ""
        parts.append(f"  | {name}{sep}")
    parts.append("")
    parts.append("export type SidecarWsMessage = SidecarWsServerMessage;")
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    ts = generate_ts()
    OUT.write_text(ts, encoding="utf-8")
    protocol = export_ws_protocol_json()
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(protocol['server_events'])} server events)")


if __name__ == "__main__":
    main()
